// Generated by IB v0.6.0 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>

@interface AppDelegate: UIResponder <UIApplicationDelegate>
@end

@interface GamePickerViewController: UITableViewController
-(IBAction) viewDidLoad;
-(IBAction) game:(id) indexPath;
-(IBAction) find_active_cell:(id) tableView;
-(IBAction) check_row:(id) cell;
-(IBAction) uncheck_row:(id) cell;

@end

@interface PlayerDetailsViewController: UITableViewController

@property IBOutlet UITextField * nameTextField;
@property IBOutlet UILabel * gameNameLabel;

-(IBAction) done:(id) sender;
-(IBAction) cancel:(id) sender;
-(IBAction) select_game:(id) game;

@end

@interface PlayersViewController: UITableViewController
-(IBAction) create_player:(id) name;
-(IBAction) player_details_view_cancelled:(id) controller;
-(IBAction) player_details_view_saved:(id) controller;
-(IBAction) rating_image_for:(id) score;

@end

@interface Player: NSObject
@end

@interface PlayerCell: UITableViewCell

@property IBOutlet UILabel * gameLabel;
@property IBOutlet UILabel * nameLabel;
@property IBOutlet UIImageView * ratingImage;

@end

