// Generated by IB v0.5.0 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>

@interface AppDelegate: UIResponder <UIApplicationDelegate>
@end

@interface FlickrSearchViewController: UIViewController

@property IBOutlet UISearchBar * searchBox;
@property IBOutlet UIImageView * imageView;

-(IBAction) initialize;
-(IBAction) viewDidLoad;
-(IBAction) searchBarSearchButtonClicked:(id) searchBarView;
-(IBAction) on_swipe:(id) recognizer;
-(IBAction) reset_image_view;
-(IBAction) set_active_image:(id) image;
-(IBAction) build_active_ui_image;
-(IBAction) url_for_image_api:(id) query;
-(IBAction) request;

@end

@interface GamePickerViewController: UITableViewController
-(IBAction) viewDidLoad;
-(IBAction) game:(id) indexPath;
-(IBAction) find_active_cell:(id) tableView;
-(IBAction) check_row:(id) cell;
-(IBAction) uncheck_row:(id) cell;

@end

@interface PlayerDetailsViewController: UITableViewController

@property IBOutlet UITextField * nameTextField;
@property IBOutlet UILabel * gameNameLabel;

-(IBAction) viewDidLoad;
-(IBAction) done:(id) sender;
-(IBAction) cancel:(id) sender;
-(IBAction) select_game:(id) game;
-(IBAction) update_player_properties;
-(IBAction) set_game_name_label;

@end

@interface PlayersViewController: UITableViewController
-(IBAction) viewDidLoad;
-(IBAction) player_details_view_cancelled:(id) controller;
-(IBAction) player_details_view_saved:(id) controller;
-(IBAction) prepare_view_for_new_player:(id) child_view;
-(IBAction) find_player_from_index_path:(id) indexPath;
-(IBAction) rating_image_for:(id) score;
-(IBAction) child_of_view:(id) view;

@end

@interface Player: NSObject
-(IBAction) save;

@end

@interface PlayerCell: UITableViewCell

@property IBOutlet UILabel * gameLabel;
@property IBOutlet UILabel * nameLabel;
@property IBOutlet UIImageView * ratingImage;

@end

