// Generated by IB v0.5.0 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import "Stubs.h"

@implementation AppDelegate
@end

@implementation FlickrSearchViewController
@end

@implementation GamePickerViewController
@end

@implementation PlayerDetailsViewController
@end

@implementation PlayersViewController
@end

@implementation Player
@end

@implementation PlayerCell
@end

